global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'evidently_metrics'
    honor_labels: true
    static_configs:
      - targets: ['pushgateway:9091'] # hardcoded. because prometheus doesnt read env variables

  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['fastapi:8000'] # hardcoded because prometheus doesnt read env variables
