name: Behavioral Tests

on:
  push:
    paths:
      - 'src/**'


jobs:
  test:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      -
        name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.minimal
      -
        name: Test with pytest
        run: |
          python3 -m pytest
